spring:
#  datasource:
#    hikari:
#      maximum-pool-size: 30
#      minimum-idle: 10
  jpa:
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

logging:
  level:
    root: warn
    com.jipi.ticket_ledger: info
    org.springframework: warn
    org.hibernate: warn
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off

jwt:
  access-token-expiration: 3600000 # 1 hour

toss:
  payments:
    base-url: http://127.0.0.1:18080
    connect-timeout: 1s
    read-timeout: 2s

reservation:
  hold-duration: 10m
  expire-scheduler:
    fixed-delay-ms: 3600000
    batch-size: 50

payment:
  recovery-scheduler:
    batch-size: 10

cache:
  event:
    list:
      ttl: 60s
      max-size: 1
    detail:
      ttl: 5m
      max-size: 500
