CREATE TABLE payment_outbox_events
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id      UUID                                    NOT NULL,
    payment_id    BIGINT                                  NOT NULL,
    event_type    VARCHAR(50)                             NOT NULL,
    event_version INTEGER                                 NOT NULL,
    payload       JSONB                                   NOT NULL,
    status        VARCHAR(20)                             NOT NULL,
    retry_count   INTEGER                                 NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMP WITH TIME ZONE,
    last_error    VARCHAR(1000),
    occurred_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    published_at  TIMESTAMP WITH TIME ZONE,
    CONSTRAINT payment_outbox_events_pkey PRIMARY KEY (id),
    CONSTRAINT payment_outbox_events_event_id_key UNIQUE (event_id),
    CONSTRAINT payment_outbox_events_transition_key UNIQUE (payment_id, event_type),
    CONSTRAINT payment_outbox_events_payment_fk FOREIGN KEY (payment_id) REFERENCES payments (id),
    CONSTRAINT payment_outbox_events_status_check
        CHECK (status IN ('PENDING', 'PUBLISHED', 'HOLD_MANUAL')),
    CONSTRAINT payment_outbox_events_retry_count_check CHECK (retry_count >= 0)
);

CREATE INDEX idx_payment_outbox_pending
    ON payment_outbox_events (status, next_retry_at, id);
