CREATE TABLE payment_event_inbox
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id        UUID                                    NOT NULL,
    event_type      VARCHAR(50)                             NOT NULL,
    event_version   INTEGER                                 NOT NULL,
    payment_id      BIGINT                                  NOT NULL,
    payload_hash    CHAR(64)                                NOT NULL,
    topic           VARCHAR(255)                            NOT NULL,
    record_partition INTEGER                                NOT NULL,
    record_offset   BIGINT                                  NOT NULL,
    received_at     TIMESTAMP WITH TIME ZONE                NOT NULL,
    processed_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT payment_event_inbox_pkey PRIMARY KEY (id),
    CONSTRAINT payment_event_inbox_event_id_key UNIQUE (event_id),
    CONSTRAINT payment_event_inbox_record_key UNIQUE (topic, record_partition, record_offset)
);

CREATE INDEX idx_payment_event_inbox_processed_at
    ON payment_event_inbox (processed_at, id);

CREATE TABLE payment_event_audit
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id             UUID                                    NOT NULL,
    event_type           VARCHAR(50)                             NOT NULL,
    event_version        INTEGER                                 NOT NULL,
    payment_id           BIGINT                                  NOT NULL,
    order_id             VARCHAR(100)                            NOT NULL,
    reservation_group_id BIGINT                                  NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    total_amount         INTEGER                                 NOT NULL,
    currency             VARCHAR(10)                             NOT NULL,
    occurred_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    source               VARCHAR(20)                             NOT NULL,
    payload_hash         CHAR(64)                                NOT NULL,
    recorded_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT payment_event_audit_pkey PRIMARY KEY (id),
    CONSTRAINT payment_event_audit_event_id_key UNIQUE (event_id),
    CONSTRAINT payment_event_audit_type_check
        CHECK (event_type IN ('PaymentApproved', 'PaymentCanceled')),
    CONSTRAINT payment_event_audit_source_check
        CHECK (source IN ('NORMAL', 'RECOVERY'))
);

CREATE INDEX idx_payment_event_audit_payment_id
    ON payment_event_audit (payment_id, occurred_at, id);
