ALTER TABLE payment_outbox_events
    ADD COLUMN payload_hash VARCHAR(64);

CREATE TABLE payment_outbox_requeue_audit
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event_id      UUID                                    NOT NULL,
    payment_id    BIGINT                                  NOT NULL,
    admin_user_id BIGINT                                  NOT NULL,
    reason        VARCHAR(200)                            NOT NULL,
    requeued_at   TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT payment_outbox_requeue_audit_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_payment_outbox_requeue_audit_event
    ON payment_outbox_requeue_audit (event_id, requeued_at, id);
