CREATE TABLE events
(
    booking_open_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    venue           VARCHAR(100)                            NOT NULL,
    title           VARCHAR(200)                            NOT NULL,
    description     VARCHAR(1000),
    CONSTRAINT events_pkey PRIMARY KEY (id)
);

CREATE TABLE payments
(
    amount               INTEGER                                 NOT NULL,
    approved_at          TIMESTAMP WITHOUT TIME ZONE,
    canceled_at          TIMESTAMP WITHOUT TIME ZONE,
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requested_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    reservation_group_id BIGINT,
    currency             VARCHAR(10)                             NOT NULL,
    status               VARCHAR(20)                             NOT NULL,
    method               VARCHAR(50),
    pg_status            VARCHAR(50),
    order_id             VARCHAR(100)                            NOT NULL,
    payment_key          VARCHAR(200),
    CONSTRAINT payments_pkey PRIMARY KEY (id)
);

CREATE TABLE refresh_tokens
(
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    last_used_at TIMESTAMP WITHOUT TIME ZONE,
    revoked_at   TIMESTAMP WITHOUT TIME ZONE,
    user_id      BIGINT                                  NOT NULL,
    jti          VARCHAR(100)                            NOT NULL,
    token_hash   VARCHAR(255)                            NOT NULL,
    CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id)
);

CREATE TABLE reservation_groups
(
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    expires_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    status     VARCHAR(20)                             NOT NULL,
    CONSTRAINT reservation_groups_pkey PRIMARY KEY (id)
);

CREATE TABLE reservations
(
    canceled_at          TIMESTAMP WITHOUT TIME ZONE,
    expires_at           TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reservation_group_id BIGINT,
    reserved_at          TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    seat_id              BIGINT                                  NOT NULL,
    user_id              BIGINT                                  NOT NULL,
    status               VARCHAR(20)                             NOT NULL,
    CONSTRAINT reservations_pkey PRIMARY KEY (id)
);

CREATE TABLE schedules
(
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE seats
(
    price       INTEGER                                 NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    schedule_id BIGINT                                  NOT NULL,
    grade       VARCHAR(20)                             NOT NULL,
    seat_number VARCHAR(20)                             NOT NULL,
    status      VARCHAR(20)                             NOT NULL,
    CONSTRAINT seats_pkey PRIMARY KEY (id)
);

CREATE TABLE users
(
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(50)                             NOT NULL,
    email      VARCHAR(100)                            NOT NULL,
    password   VARCHAR(225)                            NOT NULL,
    role       VARCHAR(255)                            NOT NULL,
    status     VARCHAR(255)                            NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

ALTER TABLE payments
    ADD CONSTRAINT payments_order_id_key UNIQUE (order_id);

ALTER TABLE payments
    ADD CONSTRAINT payments_payment_key_key UNIQUE (payment_key);

ALTER TABLE payments
    ADD CONSTRAINT payments_reservation_group_id_key UNIQUE (reservation_group_id);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT uk_refresh_token_jti UNIQUE (jti);

ALTER TABLE seats
    ADD CONSTRAINT uk_seat_schedule_seat_number UNIQUE (schedule_id, seat_number);

ALTER TABLE users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE schedules
    ADD CONSTRAINT fk3yybbfs7c4a3p64w3pcxku2ly FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT fk57amums6j9fkqwbpw4oceyw9i FOREIGN KEY (seat_id) REFERENCES seats (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT fkb5g9io5h54iwl2inkno50ppln FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;

ALTER TABLE reservations
    ADD CONSTRAINT fkenxi2fgy9t60ej2abg4byc4m1 FOREIGN KEY (reservation_group_id) REFERENCES reservation_groups (id) ON DELETE NO ACTION;

ALTER TABLE seats
    ADD CONSTRAINT fkfbw4qi0nr80b7o8kpb25gy2q7 FOREIGN KEY (schedule_id) REFERENCES schedules (id) ON DELETE NO ACTION;

ALTER TABLE payments
    ADD CONSTRAINT fkghyl1awumqfi6osl2fddf9bte FOREIGN KEY (reservation_group_id) REFERENCES reservation_groups (id) ON DELETE NO ACTION;

ALTER TABLE reservation_groups
    ADD CONSTRAINT fkqutwax177x05m0sk34ygchbdn FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE NO ACTION;
